### ISSUE TITLE
[Feature Request] Let `log_path` overwrites filename for each handler separately

### ISSUE THREAD

**Issue by ZeroRin** [Dragon2fly/logger_tt#18]
In `log_config.json` it is possible to initialize multiple file handlers with different destination files, but when `log_path` is given, `filename` for every file handler is modified so that all of them point to the same file. I think it is better to enable `log_path` to recieve a dict as well. Passing a string keeps the current behavior and passing a dict assigns a filename for each handler according to their key in config file.

**Comment by Dragon2fly** [comment]
I think it is a good idea. Can you implement it in the [ensure_path](https://github.com/Dragon2fly/logger_tt/blob/7a88916980b916e72df4f09783f60552b589c189/logger_tt/__init__.py#L59) function?

**Comment by ZeroRin** [comment]
Yes, I have implemented it [here](https://github.com/ZeroRin/logger_tt/commit/674aa52faa4f8759d5e0e6bb8ef1fb0facf2939b#diff-782f70b009cc5820c7c993d3e434982c08d2a92ad255674c9b52c1b73221ce09)

For adding testcases, shall I create a separate `log_config.json` for test purpose only or modify the original one so that we may demostrate this feature in documents?

**Comment by Dragon2fly** [comment]
Yes, you will create a new config file but not directly.
You could reference this [test case](https://github.com/Dragon2fly/logger_tt/blob/7a88916980b916e72df4f09783f60552b589c189/tests/test_multiprocessing.py#L105) for how to modify and save a new the log config file on the fly.
The referenced test case uses `log_config.yaml` but the logic for `log_config.json` is also similar.
