### ISSUE TITLE
pytest errors

### ISSUE THREAD

**Issue by nonnull-ca** [Dragon2fly/logger_tt#24]
While attempting to add tests for #23, I hit a couple of pytest errors:

1: `test_inspector` [is hardcoded](https://github.com/Dragon2fly/logger_tt/blob/ef5a97d2e8ea355915f8dbd5d50e05bfd8091cb4/tests/test_inspector.py#L246) to look for `D:\pycharm_projects` in the exception object. As I am running in a different directory, this test fails.

2: [Many](https://github.com/Dragon2fly/logger_tt/blob/ef5a97d2e8ea355915f8dbd5d50e05bfd8091cb4/tests/conftest.py#L9) [different](https://github.com/Dragon2fly/logger_tt/blob/ef5a97d2e8ea355915f8dbd5d50e05bfd8091cb4/tests/test_edit_log_path.py#L8) [tests](https://github.com/Dragon2fly/logger_tt/blob/ef5a97d2e8ea355915f8dbd5d50e05bfd8091cb4/tests/test_inspector.py#L12) [use](https://github.com/Dragon2fly/logger_tt/blob/ef5a97d2e8ea355915f8dbd5d50e05bfd8091cb4/tests/test_multiprocessing.py#L13) [`cwd`](https://github.com/Dragon2fly/logger_tt/blob/ef5a97d2e8ea355915f8dbd5d50e05bfd8091cb4/tests/test_recur_exception.py#L7) [when](https://github.com/Dragon2fly/logger_tt/blob/ef5a97d2e8ea355915f8dbd5d50e05bfd8091cb4/tests/test_simple.py#L16) [they](https://github.com/Dragon2fly/logger_tt/blob/ef5a97d2e8ea355915f8dbd5d50e05bfd8091cb4/tests/test_theading.py#L8) should use e.g. `os.path.realpath(__file__)` instead.

3: Even though the main code works with [either](https://github.com/Dragon2fly/logger_tt/blob/ef5a97d2e8ea355915f8dbd5d50e05bfd8091cb4/logger_tt/__init__.py#L86) `pyyaml` or `ruamel.yaml`, `test_multiprocessing` [is hardcoded](https://github.com/Dragon2fly/logger_tt/blob/ef5a97d2e8ea355915f8dbd5d50e05bfd8091cb4/tests/test_multiprocessing.py#L5) to use `ruamel.yaml` - and Murphy's law meant that of course I had only `pyyaml` installed.

All easily fixed - I'll throw up a PR in a bit. Don't know where this project falls on the sliding scale between 'a billion tiny PRs' and 'one huge PR'.

**Comment by Dragon2fly** [comment]
Thanks for your finding.

> 1: test_inspector [is hardcoded](https://github.com/Dragon2fly/logger_tt/blob/ef5a97d2e8ea355915f8dbd5d50e05bfd8091cb4/tests/test_inspector.py#L246) to look for D:\pycharm_projects in the exception object. As I am running in a different directory, this test fails.

Sorry, I was in a hurry at that time so I left it as is. Should have used regex instead.

> 2: [Many](https://github.com/Dragon2fly/logger_tt/blob/ef5a97d2e8ea355915f8dbd5d50e05bfd8091cb4/tests/conftest.py#L9) [different](https://github.com/Dragon2fly/logger_tt/blob/ef5a97d2e8ea355915f8dbd5d50e05bfd8091cb4/tests/test_edit_log_path.py#L8) [tests](https://github.com/Dragon2fly/logger_tt/blob/ef5a97d2e8ea355915f8dbd5d50e05bfd8091cb4/tests/test_inspector.py#L12) [use](https://github.com/Dragon2fly/logger_tt/blob/ef5a97d2e8ea355915f8dbd5d50e05bfd8091cb4/tests/test_multiprocessing.py#L13) [cwd](https://github.com/Dragon2fly/logger_tt/blob/ef5a97d2e8ea355915f8dbd5d50e05bfd8091cb4/tests/test_recur_exception.py#L7) [when](https://github.com/Dragon2fly/logger_tt/blob/ef5a97d2e8ea355915f8dbd5d50e05bfd8091cb4/tests/test_simple.py#L16) [they](https://github.com/Dragon2fly/logger_tt/blob/ef5a97d2e8ea355915f8dbd5d50e05bfd8091cb4/tests/test_theading.py#L8) should use e.g. os.path.realpath(__file__) instead.

Pytest is invoked inside that `tests` directory, so `Path.cwd()` is fine. 
The longer version if needed, will be `Path(__file__).parent`.
The reason for `cwd` is the `tests` directory is that some tests need to call the external py files, which are in the same directory.
So using the `tests` directory as `cwd` made writing tests easier.
If there is a reason for using `os.path.realpath(__file__)`, please let me know.

> 3: Even though the main code works with [either](https://github.com/Dragon2fly/logger_tt/blob/ef5a97d2e8ea355915f8dbd5d50e05bfd8091cb4/logger_tt/__init__.py#L86) pyyaml or ruamel.yaml, test_multiprocessing [is hardcoded](https://github.com/Dragon2fly/logger_tt/blob/ef5a97d2e8ea355915f8dbd5d50e05bfd8091cb4/tests/test_multiprocessing.py#L5) to use ruamel.yaml - and Murphy's law meant that of course I had only pyyaml installed.

Yeah, I should have rewritten that better. But since the `ruamel.yaml` was supported later, I used it over `pyyaml`.
