### ISSUE TITLE
Stub file not found for logger_tt

### ISSUE THREAD

**Issue by AlphonsG** [Dragon2fly/logger_tt#7]
Thanks a lot for this software. When importing logger_tt Pylance in VSCode complains that "Stub file not found for "logger_tt" Pylance([reportMissingTypeStubs](https://github.com/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md#diagnostic-severity-rules))". I noticed that you added a stub file to the repo [here](https://github.com/Dragon2fly/logger_tt/blob/master/logger_tt/__init__.pyi) (thanks for the effort too) but when when I look under `...\Lib\site-packages\logger_tt` in my local install (which was via pip) the stub file is not present. When I manually copied the stub file to `<my-personal-python-project-root-dir>\typings\logger_tt\` the file is detected and type hinting works as intended.

I suspect that when logger_tt is packaged the stub file is not being included for some reason in the package files. I'm also using version 1.7.0 and python 3.10.

**Comment by Dragon2fly** [comment]
Thank you for your finding. The stub file will be included in the next release.

**Comment by AlphonsG** [comment]
Thanks!
